FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS build  
WORKDIR /src  
RUN git clone --single-branch -b single-library https://github.com/AleksWasiluk/SimpleDotNetCoreApp.git
RUN cd SimpleDotNetCoreApp
RUN dotnet publish "./TestApi/TestApi.csproj" --configuration=Release --runtime=linux-x64 --output=/app  
  
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
WORKDIR /app
COPY --from=build /app .  
ENTRYPOINT ["dotnet", "TestApi.dll"]